-- =====================================================================
-- Phase 1 - Core Foundation
-- MySQL/MariaDB schema. InnoDB, utf8mb4, DECIMAL for money (none needed
-- in this phase yet), CHAR(36) UUIDs generated by the application layer
-- (never a DB default) per CPANEL_MYSQL_IMPLEMENTATION_PLAN.md's Target
-- Folder Architecture / MySQL Schema Migration Order sections.
-- =====================================================================

-- Tracks which schema/*.sql files have been applied - lets database/migrate.php
-- be safely re-run (no-op on a file already applied), the PHP-side
-- equivalent of `supabase db reset` being idempotent.
CREATE TABLE IF NOT EXISTS schema_migrations (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Five roles, unchanged from the original Postgres user_role enum. A
-- plain MySQL ENUM is acceptable here because this set has never grown
-- across five phases of the original implementation (unlike
-- exception_type/journal_source_type, which DID grow - see
-- MIGRATION_TO_CPANEL_MYSQL_PLAN.md sec.2 item 5 for that distinction).
CREATE TABLE IF NOT EXISTS profiles (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  role ENUM('super_admin', 'accounting', 'finance_manager', 'management', 'investor') NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_profiles_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DB-backed sessions (never PHP's default file-based handler on shared
-- hosting - see CPANEL_MYSQL_IMPLEMENTATION_PLAN.md's Auth/Session
-- Architecture section for why). payload holds the serialized session
-- data written by App\Services\DbSessionHandler.
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(128) NOT NULL PRIMARY KEY,
  user_id CHAR(36) NULL,
  payload LONGTEXT NOT NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  last_activity DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_sessions_user_id (user_id),
  KEY idx_sessions_last_activity (last_activity),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_password_reset_token_hash (token_hash),
  KEY idx_password_reset_user (user_id),
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Login attempt log, used by AuthService for rate limiting (no
-- persistent in-memory limiter is available on shared hosting - see
-- implementation plan's Auth architecture section). Indexed by
-- identifier (email or IP) + attempted_at for the "N failures in the
-- last M minutes" query.
CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  identifier VARCHAR(255) NOT NULL,
  ip_address VARCHAR(45) NULL,
  succeeded TINYINT(1) NOT NULL,
  attempted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_login_attempts_identifier_time (identifier, attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit trail - every mutating Service method ends with a write here,
-- mirroring the original Postgres audit_log table exactly (same column
-- shape) so its role in the system is unchanged, only its host.
CREATE TABLE IF NOT EXISTS audit_log (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id CHAR(36) NULL,
  action VARCHAR(100) NOT NULL,
  entity_table VARCHAR(100) NOT NULL,
  entity_id CHAR(36) NULL,
  old_value JSON NULL,
  new_value JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_audit_entity (entity_table, entity_id),
  KEY idx_audit_user (user_id),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
